const BASE_URL = "https://server.predicto.ai/api/v1/search/reporting";

export interface PredictoRow {
  date: string;
  custom_channel_id: string;
  revenue_usd: number;
  clicks: number;
  funnel_clicks: number;
  funnel_impressions: number;
  funnel_requests: number;
  requests: number;
  impressions: number;
}

interface ApiRow {
  date: string;
  custom_channel_id: string;
  estimated_revenue?: number | string;
  clicks?: number | string;
  funnel_clicks?: number | string;
  funnel_impressions?: number | string;
  funnel_requests?: number | string;
  requests?: number | string;
  impressions?: number | string;
}

interface ApiResponse {
  status: string;
  data: ApiRow[];
}

// Shared core — both Predicto (Snap traffic) and Predicto FB (Facebook traffic)
// hit the same endpoint/shape; only the API token differs.
async function fetchPredictoWithToken(
  label: string,
  apiToken: string | null,
  startDate: string,
  endDate: string
): Promise<PredictoRow[]> {
  if (!apiToken) {
    console.warn(`[${label}] token not set — skipping`);
    return [];
  }

  const params = new URLSearchParams({
    start_date: startDate,
    end_date: endDate,
    metrics: "revenue,clicks,funnel_clicks,funnel_impressions,funnel_requests,requests,impressions",
    dimensions: "date,custom_channel_id",
  });

  const res = await fetch(`${BASE_URL}?${params}`, {
    headers: { Authorization: `Bearer ${apiToken}` },
    cache: "no-store",
  });

  if (!res.ok) {
    const body = await res.text().catch(() => "");
    // TEMP DEBUG — remove once the 401 root cause is confirmed. Never logs the
    // token itself, only length + first/last char, to check for whitespace/
    // truncation without exposing the secret.
    console.error(
      `[${label}] auth debug: len=${apiToken.length} first=${apiToken[0]} last=${apiToken[apiToken.length - 1]}`
    );
    throw new Error(`Predicto API error ${res.status}: ${body}`);
  }

  const json = await res.json() as ApiResponse;
  if (json.status !== "success") {
    throw new Error(`Predicto API returned status: ${json.status}`);
  }

  return (json.data ?? []).map((r) => ({
    date: r.date,
    custom_channel_id: r.custom_channel_id ?? "",
    revenue_usd: Number(r.estimated_revenue ?? 0),
    clicks: Number(r.clicks ?? 0),
    funnel_clicks: Number(r.funnel_clicks ?? 0),
    funnel_impressions: Number(r.funnel_impressions ?? 0),
    funnel_requests: Number(r.funnel_requests ?? 0),
    requests: Number(r.requests ?? 0),
    impressions: Number(r.impressions ?? 0),
  }));
}

// Predicto — revenue generated by Snap traffic.
export async function fetchPredictoReport(startDate: string, endDate: string): Promise<PredictoRow[]> {
  return fetchPredictoWithToken("predicto", process.env.PREDICTO_API_TOKEN ?? null, startDate, endDate);
}

// Predicto FB — same API, separate token, revenue generated by Facebook (Meta) traffic.
export async function fetchPredictoFbReport(startDate: string, endDate: string): Promise<PredictoRow[]> {
  return fetchPredictoWithToken("predicto-fb", process.env.PREDICTO_FB_API_TOKEN ?? null, startDate, endDate);
}
